common-settings {
  scala-version = "2.13.16"
}

core = [
  "org.junit.jupiter:junit-jupiter-api:*:test"
  "org.junit:junit-bom:5.10.1:bom"
]

app = [
  "org.junit.jupiter:junit-jupiter-params:*:test"
]
