updates.cooldown = { minimumAge = "36500 days" }

dependencyOverrides = [
  {
    dependency = { groupId = "org.typelevel", artifactId = "cats-core" }
    cooldown   = { minimumAge = "1 second" }
  }
]
