myproject {
  scala-version = "2.13.16"
  dependencies = [
    "org.typelevel::cats-core:2.10.0"
    { dependency = "org.typelevel::kind-projector:0.13.3:compiler-plugin", cross-version = "full" }
    "com.google.protobuf:protobuf-java:3.25.1:protobuf"
    "org.scalameta::munit:1.2.1:test"
    "javax.servlet:javax.servlet-api:4.0.1:provided"
  ]
}
