myproject {
  scala-versions = ["2.13.16", "3.3.6"]
  dependencies = [
    "org.scalameta::munit:1.2.1:test"
    "org.typelevel::cats-core:2.10.0"
    { dependency = "com.google.guava:guava:33.4.0-jre", note = "Java library" }
  ]
}

sbt-build = [
  "org.scalameta:sbt-scalafmt:2.5.6:sbt-plugin"
  "ch.epfl.scala:sbt-scalafix:0.14.5:sbt-plugin"
]
