common-settings {
  scala-version = "2.13.16"
  dependencies = [
    "com.fasterxml.jackson:jackson-bom:2.17.2:bom"
  ]
}

myproject = [
  "com.fasterxml.jackson.core:jackson-databind:2.17.2"
  "com.fasterxml.jackson.core:jackson-core:=2.17.2"
  "com.fasterxml.jackson.core:jackson-annotations:^2.17.1"
  "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:*"
  "com.fasterxml.jackson.module::jackson-module-scala:2.17.1"
  "org.junit:junit-bom:5.10.3:bom"
  "org.junit.jupiter:junit-jupiter-api:5.10.3:test"
  "org.scalameta::munit:1.0.0:test"
]

otherproject = [
  "com.fasterxml.jackson.core:jackson-annotations:2.17.2"
]
