sbt-build {
  java-version = "17"
  dependencies = []
}

myproject = [
  "org.typelevel::cats-core:2.10.0"
]

otherproject {
  java-version = "21"
  dependencies = [
    "org.typelevel::cats-core:2.10.0"
  ]
}
