common-settings {
  scala-version = "2.13.16"
  dependencies = [
    "com.fasterxml.jackson.core:jackson-databind:*"
    "com.fasterxml.jackson:jackson-bom:2.16.0:bom"
  ]
}

myproject = [
  "org.junit.jupiter:junit-jupiter-api:*:test"
  "org.junit:junit-bom:5.10.0:bom"
  "org.typelevel::cats-core:{{catsVersion}}"
]

app = [
  "org.junit.jupiter:junit-jupiter-params:*:test"
]
